baseURL: https://eternity.bora.sh # todo: change site url.
title: miguehm # todo: change site name.
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.

params:
  image: /images/banner.png
  logo: logo.png # todo: add your custom logo to static/
  subtitle: Capturando el momento # todo: change default subtitle for your website.
  copyright: Todos los derechos reservados. # todo: set your copyright type.
  author: Miguel Hernández Moreno # todo: set your full name.
  dontShowSource: false # please, do not do this :) ... I won't uwu
  portfolio:
    columns:
      desktop:
        nature: 4
        archive: 5
        people: 2
        experimental: 3
        default: 3
      mobile:
        default: 2
        archive: 3
        people: 2
        experimental: 2
  socials:
    # todo: change these links.
    - icon: 'fab fa-instagram fa-lg'
      url: 'https://instagram.com/_miguehm'
      landing: true
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto:cm.mahm1@gmail.com'
      landing: true
  #  - icon: 'fab fa-linkedin-in fa-lg'
  #    url: 'https://linkedin.bora.sh/in/eternity'
  homepage: "/work" # homepage link, mostly same with menu.main[0]
  specialPages:
    - work
    - archive
  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.
  disableWelcomePageBackground: false # disables the background image on the homepage
  plausible: '' # todo: set your plausible id.
  disableRadius: false
  moveIt: true  # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: ":filename/"

menu:
  main:
    - name: general
      url: /work/
      weight: 1
    - name: retrato
      url: /tags/people/
      weight: 2
    - name: street photo
      url: /tags/street-photo/
      weight: 3
    - name: experimentos
      url: /tags/experimental/
      weight: 4
    - name: archivo
      url: /tags/archive/
      weight: 5
    - name: acerca de
      url: /about/
      weight: 6
